<a href="https://colab.research.google.com/github/sakshi0100/ML-Intern/blob/master/trade_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive',force_remount=False)

In [0]:
import pandas
df=pandas.read_csv('/content/drive/My Drive/dataset/data.csv')
df.head()

        Date  Symbol  ...  Total Traded Quantity   Turnover (in Lakhs)
0  13-Apr-20      LT  ...                9462929              80158.97
1  09-Apr-20      LT  ...                6410629              52338.49
2  08-Apr-20      LT  ...                6151093              50037.53
3  07-Apr-20      LT  ...                5769216              46404.57
4  03-Apr-20      LT  ...                4268501              33009.75

[5 rows x 10 columns]

In [0]:
df[' Mean']=df.iloc[:,4:8].mean(axis=1)
df[' Median']=df.iloc[:,4:8].median(axis=1)
df[' Mode']=df.iloc[:,lambda df: [3]].mode(axis=1)
df

         Date  Symbol  Series  ...       Mean    Median     Mode
0   13-Apr-20      LT      EQ  ...   852.5500   864.925   812.80
1   09-Apr-20      LT      EQ  ...   814.1375   808.900   834.35
2   08-Apr-20      LT      EQ  ...   811.2000   807.550   804.00
3   07-Apr-20      LT      EQ  ...   801.9625   801.925   805.00
4   03-Apr-20      LT      EQ  ...   777.8875   778.825   791.10
5   01-Apr-20      LT      EQ  ...   782.2125   774.950   806.85
6   31-Mar-20      LT      EQ  ...   808.2000   809.300   820.00
7   30-Mar-20      LT      EQ  ...   800.9125   798.825   801.00
8   27-Mar-20      LT      EQ  ...   845.0125   839.025   867.90
9   26-Mar-20      LT      EQ  ...   819.1875   840.150   787.75
10  25-Mar-20      LT      EQ  ...   742.6875   767.375   697.20
11  24-Mar-20      LT      EQ  ...   711.4125   708.950   755.00
12  23-Mar-20      LT      EQ  ...   740.2500   722.525   809.00
13  20-Mar-20      LT      EQ  ...   856.4500   858.350   849.00
14  19-Mar-20      LT      EQ  ...   850.9500   841.050   873.90
15  18-Mar-20      LT      EQ  ...   922.8250   908.275   968.00
16  17-Mar-20      LT      EQ  ...   963.7250   954.875   972.00
17  16-Mar-20      LT      EQ  ...   985.1500   968.350  1014.25
18  13-Mar-20      LT      EQ  ...  1015.4750  1055.725   950.00
19  12-Mar-20      LT      EQ  ...  1027.6750  1018.275  1070.00
20  11-Mar-20      LT      EQ  ...  1110.6750  1117.975  1090.00
21  09-Mar-20      LT      EQ  ...  1101.5125  1101.475  1135.80
22  06-Mar-20      LT      EQ  ...  1152.1500  1156.875  1148.00
23  05-Mar-20      LT      EQ  ...  1179.1000  1181.475  1180.10
24  04-Mar-20      LT      EQ  ...  1174.6000  1176.275  1185.00
25  03-Mar-20      LT      EQ  ...  1178.3250  1182.225  1166.00
26  02-Mar-20      LT      EQ  ...  1169.4250  1157.400  1205.00
27  28-Feb-20      LT      EQ  ...  1184.2750  1189.325  1189.65
28  27-Feb-20      LT      EQ  ...  1209.0000  1209.525  1212.35
29  26-Feb-20      LT      EQ  ...  1217.5125  1213.025  1235.00
30  25-Feb-20      LT      EQ  ...  1247.4250  1241.950  1262.20
31  24-Feb-20      LT      EQ  ...  1261.0375  1259.800  1271.90
32  20-Feb-20      LT      EQ  ...  1281.7000  1281.300  1279.90
33  19-Feb-20      LT      EQ  ...  1284.6250  1281.450  1298.00
34  18-Feb-20      LT      EQ  ...  1282.6500  1287.175  1281.50
35  17-Feb-20      LT      EQ  ...  1284.1375  1280.850  1297.00
36  14-Feb-20      LT      EQ  ...  1295.9750  1294.175  1295.00
37  13-Feb-20      LT      EQ  ...  1292.0250  1291.625  1299.00
38  12-Feb-20      LT      EQ  ...  1294.0375  1298.150  1289.10
39  11-Feb-20      LT      EQ  ...  1289.0250  1286.575  1292.00
40  10-Feb-20      LT      EQ  ...  1285.9625  1284.150  1300.00
41  07-Feb-20      LT      EQ  ...  1301.9750  1298.750  1313.05
42  06-Feb-20      LT      EQ  ...  1317.1625  1317.300  1322.90
43  05-Feb-20      LT      EQ  ...  1310.2625  1310.525  1297.90
44  04-Feb-20      LT      EQ  ...  1294.9000  1292.375  1296.00
45  03-Feb-20      LT      EQ  ...  1287.4000  1286.850  1290.00
46  01-Feb-20      LT      EQ  ...  1309.4250  1287.000  1372.60
47  31-Jan-20      LT      EQ  ...  1369.1875  1369.650  1375.95
48  30-Jan-20      LT      EQ  ...  1366.2500  1367.600  1365.95
49  29-Jan-20      LT      EQ  ...  1364.4500  1365.375  1353.10
50  28-Jan-20      LT      EQ  ...  1346.1625  1345.825  1350.90
51  27-Jan-20      LT      EQ  ...  1350.1250  1347.800  1340.00
52  24-Jan-20      LT      EQ  ...  1352.7625  1355.600  1332.00
53  23-Jan-20      LT      EQ  ...  1327.1500  1331.375  1307.00
54  22-Jan-20      LT      EQ  ...  1298.2750  1294.550  1311.00
55  21-Jan-20      LT      EQ  ...  1304.7000  1302.225  1304.75
56  20-Jan-20      LT      EQ  ...  1311.7750  1310.350  1313.95
57  17-Jan-20      LT      EQ  ...  1309.0375  1304.100  1320.60
58  16-Jan-20      LT      EQ  ...  1322.1500  1319.150  1327.70
59  15-Jan-20      LT      EQ  ...  1325.8125  1323.550  1325.60

[60 rows x 13 columns]

**To convert into excel sheet**

In [0]:
df.to_excel('modified.xlsx')